### ISSUE TITLE
Bom Submission 

### ISSUE THREAD

**Issue by timChase98** [kbowers95/Catch-The-Light-Game#1]
- [x] Readme should contain project information 
- [x] Submissions must be in the form of a CSV in a release
- [x] Parts should be organized by value not designator
- [x] Missing Columns
  - [x] Tolerance and rating
  - [x] Ordering information
- [x] Remove extraneous columns

**Comment by kbowers95** [comment]
Sorry getting it fixed right now!

________________________________

**Comment by kbowers95** [comment]
Hey Chase;
Last thing just to make sure.. Tolerance and rating is the speed in which each component runs? ex. 1MIPS per MHz and so on? And the ordering information is just how much and the amount?
Thank you,
Kenneth Bowers
________________________________
